SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP DATABASE IF EXISTS `mysql_benchmark`;
CREATE DATABASE IF NOT EXISTS `mysql_benchmark` DEFAULT CHARACTER SET utf8mb4;

USE `mysql_benchmark`

CREATE TABLE IF NOT EXISTS `buzz` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `col1` INT UNSIGNED NOT NULL,
  `col2` VARCHAR(255) NOT NULL,
  `col3` VARCHAR(255) NOT NULL,
  `col4` VARCHAR(255) NOT NULL,
  `col5` VARCHAR(255) NOT NULL,
  `col6` VARCHAR(255) NOT NULL,
  `col7` VARCHAR(255) NOT NULL,
  `col8` VARCHAR(255) NOT NULL,
  `col9` VARCHAR(255) NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  INDEX `idx_updated_at` (`updated_at` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
CHARSET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `sub_buzz` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `buzz_id` INT UNSIGNED NOT NULL,
  `col1` INT UNSIGNED NOT NULL,
  `col2` VARCHAR(255) NOT NULL,
  `col3` VARCHAR(255) NOT NULL,
  `col4` VARCHAR(255) NOT NULL,
  `col5` VARCHAR(255) NOT NULL,
  `col6` VARCHAR(255) NOT NULL,
  `col7` VARCHAR(255) NOT NULL,
  `col8` VARCHAR(255) NOT NULL,
  `col9` VARCHAR(255) NOT NULL,
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  INDEX `idx_buzz_id` (`buzz_id` ASC),
  INDEX `idx_updated_at` (`updated_at` ASC),
  CONSTRAINT `sub_buzz_buzz_id`
    FOREIGN KEY (`buzz_id`)
    REFERENCES `buzz` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
CHARSET = utf8mb4
COLLATE = utf8mb4_unicode_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
